http:
  routers:
    traefik-dashboard:
      rule: "Host(`traefik.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: api@internal
      tls:
        certResolver: le
      middlewares:
        - all-ipwhitelist

    ombi:
      rule: "Host(`ombi.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: ombi-service
      tls:
        certResolver: le

    tautulli:
      rule: "Host(`tautulli.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: tautulli-service
      tls:
        certResolver: le
      middlewares:
        - all-ipwhitelist

    overseerr:
      rule: "Host(`overseerr.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: overseerr-service
      tls:
        certResolver: le
      middlewares:
        - all-ipwhitelist

    sonarr:
      rule: "Host(`sonarr.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: sonarr-service
      tls:
        certResolver: le
      middlewares:
        - all-ipwhitelist

    radarr:
      rule: "Host(`radarr.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: radarr-service
      tls:
        certResolver: le
      middlewares:
        - all-ipwhitelist

    nzbget:
      rule: "Host(`nzbget.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: nzbget-service
      tls:
        certResolver: le
      middlewares:
        - all-ipwhitelist

    lidarr:
      rule: "Host(`lidarr.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: lidarr-service
      tls:
        certResolver: le
      middlewares:
        - all-ipwhitelist

    ai:
      rule: "Host(`ai.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: ai-service
      tls:
        certResolver: le
      middlewares:
        - all-ipwhitelist

    heimdall:
      rule: "Host(`heimdall.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: heimdall-service
      tls:
        certResolver: le
      middlewares:
        - all-ipwhitelist

    organizr:
      rule: "Host(`organizr.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: organizr-service
      tls:
        certResolver: le
      middlewares:
        - all-ipwhitelist

    phpmyadmin:
      rule: "Host(`phpmy.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: phpmyadmin-service
      tls:
        certResolver: le
      middlewares:
        - all-ipwhitelist

    adminer:
      rule: "Host(`adminer.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: adminer-service
      tls:
        certResolver: le
      middlewares:
        - all-ipwhitelist

  services:
    ombi-service:
      loadBalancer:
        servers:
          - url: "http://localhost:3579"

    tautulli-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8181"

    overseerr-service:
      loadBalancer:
        servers:
          - url: "http://localhost:5055"

    sonarr-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8989"

    radarr-service:
      loadBalancer:
        servers:
          - url: "http://localhost:7878"

    nzbget-service:
      loadBalancer:
        servers:
          - url: "http://localhost:6789"

    lidarr-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8686"

    ai-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8082"

    heimdall-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8282"

    organizr-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8888"

    phpmyadmin-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8083"

    adminer-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8090"

  middlewares:
    all-ipwhitelist:
      ipAllowList:
        sourceRange:
          - "127.0.0.1/32"
          - "10.20.2.0/24"
          - "70.177.105.92/32"
          - "10.20.6.1/24" 